Warning messages:
1: In text.default(xy$x, xy$y + 0.5 * cxy[2L], rows[left.child],  ... :
  "use.n." is not a graphical parameter
2: In text.default(xy$x[leaves], xy$y[leaves] - 0.5 * cxy[2L],  ... :
  "use.n." is not a graphical parameter
3: In doTryCatch(return(expr), name, parentenv, handler) :
  "use.n." is not a graphical parameter
4: In doTryCatch(return(expr), name, parentenv, handler) :
  "use.n." is not a graphical parameter
5: In doTryCatch(return(expr), name, parentenv, handler) :
  "use.n." is not a graphical parameter
6: In doTryCatch(return(expr), name, parentenv, handler) :
  "use.n." is not a graphical parameter

