# Basics in Programming in R ----
#######################################################################################
#######################################################################################
#######################################################################################
#######################################################################################
# - [-] - Variables ----
x = 1 # store a integer/number into the env. 
# ... notice the variable is stored in the R env as a "value".
# ...  this is because the type of value stored. 
# ... note, all types of values/objects can be stored. 
print(x) # print the stored variable.
a = 5
b = 5
c = a + b # perform mathematical operations 
string = "Adding 5+5= "
print(c(string, c)) # to bind ibjects, they have to be contained in an object. 
# ... think of it like storing smaller objects within objects, ...
# ... or better yet piping data into objects.
#######################################################################################
#######################################################################################
#######################################################################################
#######################################################################################
# - [-] - Lists ----
list = c(1,2,3) # a c() function creates a list, really a vector, but mainly the samething at least for this class.
list = 1:3
list = list(1,2,3)
emp_list = c() # empty lists may be created to fill with data later on in the code process.
print(list)
print(emp_list)
#######################################################################################
#######################################################################################
#######################################################################################
#######################################################################################
# - [-] - List Indexing ----
list[1] # index the 1st object within the list. 
list[2:3] # index the 1st to the 3rd object contained in the list. 
# ... not the order of the container may be altered and will ultimately change the index 
# ... positions of certain variables within the object.
list[-1] # note negations work...
#######################################################################################
#######################################################################################
#######################################################################################
#######################################################################################
# - [-] - Matrices ----
x = c(1,2,3)
matrix = as.matrix(x) # contain a list in a matrix...
print(matrix)
# or 
x = c(1,2,3)
y = c(4,5,6)
matrix = as.matrix(cbind(x,y)) # bind two lists together to make a matrix...
print(matrix)
# or 
x = c(1,2,3,4,5,6)
matrix = matrix(x, nrow = 2, ncol = 3) # create a matrix specifying the # of cols and rows...
print(matrix)
#######################################################################################
#######################################################################################
#######################################################################################
#######################################################################################
# - [-] - Dataframes ----
x = c(1,2,3)
y = c(4,5,6)
z = c("mike", "paul", "steve") # list of strings...
df = data.frame(x,y,z) # store the lists in a df...
colnames(df) = c("measure", "age", "name") # set col names...
print(df)
# note that a df is a double object, which means that it contains multi. objects...
# A df contains both a matrix and lists...
# A df contains rows and columns, but the columns are also lists that may be indexed...

print(df$name) # list of names indexed from df...
print(df[,c(1,2)]) # subset by cols...
print(df[1:2,1:2]) # subset by rows...
#######################################################################################
#######################################################################################
#######################################################################################
#######################################################################################
# - [-] - Time Series Frame ----
x = c(1,2,3) # store a list of values...
y = c(4,5,6) # store a list of values...
z = c("02/27/92", "02/27/92", "01/14/92") # list of dates...
z = as.Date(z, "%m/%d/%y") # 2nd element is the formatting of the date...
df = data.frame(x,y,z) # contain the lists in a frame first...
colnames(df) = c("measure", "age", "date") # set col names...
# as.Date converts the strings to a date format...
ts = xts::xts(df[,-c(3)], order.by = df$date) # create the ts object and order by the date col...
# make sure to remove the date variable from the frame bf creating the ts object. 
print(ts)
#######################################################################################
#######################################################################################
#######################################################################################
#######################################################################################
# - [-] - Useful Commands for to create objects ----
x = c(1,2,3) # store a list of values...
y = c(4,5,6) # store a list of values...
row = rbind(x,y) # bind objects by row...
print(row)
col = cbind(x,y) # bind objects by cols...
print(col)
#######################################################################################
#######################################################################################
#######################################################################################
#######################################################################################
# - [-] - Functions ----
a = c(1,2,3) # store a list of values...
b = c(4,5,6) # store a list of values...
df <- function(x,y) { # simply make a list of variable holders after the function...
  bind = cbind(x,y)
  df = data.frame(bind)
  colnames(df) = c("Var1", "Var2") # in-between the curly brackets start to write...
                                   # out the sequence of code you'd like to run...
                                   # and make sure to replace the objects with the...
                                   # holders you selected to list...
  print(df)
}
df(a,b) # execute the function, just feed the actually objects in place of the holders...
#######################################################################################
#######################################################################################
#######################################################################################
#######################################################################################
# - [-] - Loops ----
x = c(1,2,3) # store a list of values...
z = c("mike", "paul", "steve") # list of strings...
df = data.frame(x,z) # frame the lists...
for (i in 1:nrow(df)){ # the for loop will repeat the number of values in the list supplied *i.e.* 1:3...
  print(paste(df[i,2],"placed", df[i,1])) # paste the 1st col, "placed", and 2nd col 3 times and print...
} # end of the loop, everything should be in the curly brackets...